require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'ArticleApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ArticleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'ArticleAppClip' do
    pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
    pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
    pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
    pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
    pod 'React', :path => "../node_modules/react-native/"
    pod 'React-Core', :path => "../node_modules/react-native/"
    pod 'React-CoreModules', :path => "../node_modules/react-native/React/CoreModules"
    pod 'React-RCTActionSheet', :path => "../node_modules/react-native/Libraries/ActionSheetIOS"
    pod 'React-RCTAnimation', :path => "../node_modules/react-native/Libraries/NativeAnimation"
    pod 'React-RCTBlob', :path => "../node_modules/react-native/Libraries/Blob"
    pod 'React-RCTImage', :path => "../node_modules/react-native/Libraries/Image"
    pod 'React-RCTLinking', :path => "../node_modules/react-native/Libraries/LinkingIOS"
    pod 'React-RCTNetwork', :path => "../node_modules/react-native/Libraries/Network"
    pod 'React-RCTSettings', :path => "../node_modules/react-native/Libraries/Settings"
    pod 'React-RCTText', :path => "../node_modules/react-native/Libraries/Text"
    pod 'React-RCTVibration', :path => "../node_modules/react-native/Libraries/Vibration"
    pod 'React-Core/RCTWebSocket', :path => "../node_modules/react-native/"

    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
    # Use when hermes is enabled
    pod 'React-hermes', :path => "../node_modules/react-native/ReactCommon/hermes"
end
